# Setup
title:               Brainish
tagline:             'language of thought'
description:         ''
url:                 jan21.github.io/brainish/
baseurl:             'jan21.github.io/brainish/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jan Hůla
  url:               https://twitter.com/JanHula
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
