# Setup
title:               Brainish
tagline:             'Language Of Thought'
description:         ''
url:                 jan21.github.io/brainish/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jan Hůla
  url:               https://twitter.com/JanHula
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
